@extends('layouts.app')

@section('content')
<div class="max-w-6xl mx-auto">
    <div class="flex flex-col sm:flex-row justify-between sm:items-end gap-4 mb-6"><div><a href="{{ route('kategori.index') }}" class="text-sm text-emerald-700 font-bold"><i class="fa-solid fa-arrow-left mr-1"></i>Jenis Sampah</a><h1 class="text-2xl font-black text-gray-800 mt-2">Master Faktor Emisi</h1><p class="text-sm text-gray-500">Sumber, versi, dan tanggal berlaku disimpan untuk audit. Histori memakai snapshot.</p></div><button onclick="openFactor()" class="bg-emerald-600 text-white rounded-xl px-5 py-3 font-bold"><i class="fa-solid fa-plus mr-2"></i>Tambah Faktor</button></div>
    @if(session('success'))<div class="bg-emerald-50 border border-emerald-200 text-emerald-700 p-4 rounded-xl mb-5">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="bg-red-50 border border-red-200 text-red-700 p-4 rounded-xl mb-5"><ul class="list-disc list-inside">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="bg-amber-50 border border-amber-200 rounded-xl p-4 text-sm text-amber-800 mb-5"><i class="fa-solid fa-circle-info mr-2"></i>Jangan memasukkan faktor tanpa sumber yang dapat dipertanggungjawabkan. Faktor hasil migrasi diberi label sumber belum terdokumentasi.</div>
    <div class="space-y-3">
    @forelse($faktor as $item)
        <article class="bg-white border rounded-2xl p-5 flex flex-col lg:flex-row lg:items-center gap-4 {{ !$item->aktif ? 'opacity-60' : '' }}">
            <div class="flex-1"><div class="flex items-center gap-2"><h2 class="font-black text-gray-800">{{ $item->nama_material }}</h2><span class="text-[10px] font-black px-2 py-1 rounded-full {{ $item->aktif?'bg-emerald-100 text-emerald-700':'bg-gray-100 text-gray-600' }}">{{ $item->aktif?'AKTIF':'NONAKTIF' }}</span></div><p class="text-2xl font-black text-emerald-700 mt-2">{{ rtrim(rtrim(number_format($item->faktor_kgco2e_per_kg, 3, ',', '.'), '0'), ',') }} <small class="text-xs">kgCO₂e/kg</small></p><p class="text-xs text-gray-500 mt-2">Sumber: {{ $item->sumber ?: 'Belum dicantumkan' }} | Versi: {{ $item->versi ?: '-' }} | Dipakai {{ $item->kategori_count }} kategori</p></div>
            <div class="flex gap-2"><button onclick='openFactor(@json($item))' class="bg-gray-100 rounded-xl px-4 py-2.5 font-bold text-sm">Edit</button><form action="{{ route('faktor-emisi.toggle',$item) }}" method="POST">@csrf @method('PATCH')<button class="rounded-xl px-4 py-2.5 font-bold text-sm {{ $item->aktif?'bg-red-50 text-red-600':'bg-emerald-50 text-emerald-700' }}">{{ $item->aktif?'Nonaktifkan':'Aktifkan' }}</button></form></div>
        </article>
    @empty <div class="bg-white border rounded-2xl p-10 text-center text-gray-500">Belum ada faktor emisi.</div> @endforelse
    </div>
</div>

<div id="factorModal" class="fixed inset-0 z-[120] hidden items-center justify-center bg-gray-900/50 p-4 overflow-y-auto"><form id="factorForm" method="POST" class="bg-white rounded-2xl p-6 w-full max-w-xl my-auto">@csrf<input id="factorMethod" type="hidden" name="_method" value="POST"><h2 id="factorTitle" class="font-black text-xl">Tambah Faktor</h2><div class="grid sm:grid-cols-2 gap-4 mt-5"><div><label class="text-xs font-black text-gray-400 uppercase">Nama material</label><input id="factorName" name="nama_material" required placeholder="Contoh: Kaca" class="mt-2 w-full border rounded-xl px-4 py-3"><div class="flex flex-wrap gap-1.5 mt-2" aria-label="Contoh kategori umum">@foreach(['Kaca', 'Plastik Tebal', 'Plastik Tipis', 'Kaleng', 'Kertas Tebal', 'Kertas Tipis'] as $example)<button type="button" onclick="factorName.value=@js($example)" class="text-xs bg-emerald-50 text-emerald-700 rounded-full px-2.5 py-1 hover:bg-emerald-100">{{ $example }}</button>@endforeach</div><p class="text-xs text-gray-500 mt-2">Buat faktor umum agar jenis baru seperti botol kaca atau tumbler plastik dapat memakai kelompok yang sesuai.</p></div><div><label class="text-xs font-black text-gray-400 uppercase">Faktor kgCO₂e/kg</label><input id="factorValue" name="faktor_kgco2e_per_kg" type="number" min="0" step="0.001" placeholder="Contoh: 1,234" required class="mt-2 w-full border rounded-xl px-4 py-3"><p class="text-xs text-gray-500 mt-2">Maksimal 3 angka di belakang koma.</p></div><div><label class="text-xs font-black text-gray-400 uppercase">Versi</label><input id="factorVersion" name="versi" class="mt-2 w-full border rounded-xl px-4 py-3"></div><div><label class="text-xs font-black text-gray-400 uppercase">Tanggal berlaku</label><input id="factorDate" name="tanggal_berlaku" type="date" class="mt-2 w-full border rounded-xl px-4 py-3"></div></div><label class="block text-xs font-black text-gray-400 uppercase mt-4">Sumber</label><textarea id="factorSource" name="sumber" class="mt-2 w-full border rounded-xl px-4 py-3" rows="2"></textarea><label class="block text-xs font-black text-gray-400 uppercase mt-4">Catatan</label><textarea id="factorNotes" name="catatan" class="mt-2 w-full border rounded-xl px-4 py-3" rows="2"></textarea><input type="hidden" name="aktif" value="1"><div class="flex gap-3 mt-6"><button type="button" onclick="closeFactor()" class="flex-1 bg-gray-100 rounded-xl py-3 font-bold">Batal</button><button class="flex-1 bg-emerald-600 text-white rounded-xl py-3 font-bold">Simpan</button></div></form></div>
@push('scripts')<script>
function openFactor(item=null){factorTitle.textContent=item?'Edit Faktor':'Tambah Faktor';factorForm.action=item?@json(url('/faktor-emisi'))+'/'+item.id:@json(route('faktor-emisi.store'));factorMethod.value=item?'PUT':'POST';factorName.value=item?.nama_material||'';factorValue.value=item?Number(item.faktor_kgco2e_per_kg).toFixed(3).replace(/\.?0+$/,''):'';factorVersion.value=item?.versi||'';factorDate.value=item?.tanggal_berlaku?.substring(0,10)||'';factorSource.value=item?.sumber||'';factorNotes.value=item?.catatan||'';factorModal.classList.remove('hidden');factorModal.classList.add('flex');}
function closeFactor(){factorModal.classList.add('hidden');factorModal.classList.remove('flex');}
</script>@endpush
@endsection
