@extends('layouts.app')
@section('content')
<div class="max-w-6xl mx-auto">
 <div class="flex flex-col sm:flex-row justify-between sm:items-end gap-4 mb-6"><div><h1 class="text-2xl font-black text-gray-800">Jenis Sampah</h1><p class="text-sm text-gray-500">Pilihan operasional untuk transaksi setoran dan penjualan.</p></div><div class="flex gap-2"><a href="{{ route('kelompok-material.index') }}" class="bg-white border rounded-xl px-4 py-3 font-bold"><i class="fa-solid fa-layer-group mr-2 text-emerald-600"></i>Kelompok Material</a><button onclick="openType()" class="bg-emerald-600 text-white rounded-xl px-4 py-3 font-bold"><i class="fa-solid fa-plus mr-2"></i>Tambah Jenis</button></div></div>
 @if(session('success'))<div class="bg-emerald-50 border border-emerald-200 text-emerald-700 p-4 rounded-xl mb-5">{{ session('success') }}</div>@endif
 @if($errors->any())<div class="bg-red-50 border border-red-200 text-red-700 p-4 rounded-xl mb-5">{{ $errors->first() }}</div>@endif
 <div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">@forelse($jenis as $item)@php($editData = ['id'=>$item->id,'name'=>$item->nama,'group'=>$item->kelompok_material_id,'unit'=>$item->satuan_pencatatan->value])<article class="bg-white border rounded-2xl p-5 {{ !$item->is_active?'opacity-60':'' }}"><h2 class="font-black">{{ $item->nama }}</h2><p class="text-xs text-gray-500 mt-1">{{ $item->kelompokMaterial->nama }} · {{ $item->satuan_pencatatan->value }}</p><div class="flex gap-2 mt-4"><button onclick='openType(@json($editData))' class="flex-1 bg-gray-100 rounded-xl py-2.5 font-bold">Edit</button>@if($item->is_active)<form action="{{ route('jenis-sampah.destroy',$item) }}" method="POST">@csrf @method('DELETE')<button class="bg-red-50 text-red-600 rounded-xl px-4 py-2.5 font-bold">Nonaktifkan</button></form>@endif</div></article>@empty<div class="col-span-full bg-white border rounded-2xl p-10 text-center">Belum ada jenis sampah.</div>@endforelse</div>
</div>
<div id="typeModal" class="fixed inset-0 z-[120] hidden items-center justify-center bg-gray-900/50 p-4"><form id="typeForm" method="POST" class="bg-white rounded-2xl p-6 w-full max-w-md">@csrf<input id="typeMethod" type="hidden" name="_method" value="POST"><h2 id="typeTitle" class="font-black text-xl">Tambah Jenis Sampah</h2><label class="block text-xs font-black text-gray-400 uppercase mt-5">Nama jenis sampah</label><input id="typeName" name="nama" required class="mt-2 w-full border rounded-xl px-4 py-3"><label class="block text-xs font-black text-gray-400 uppercase mt-4">Kelompok Material</label><select id="typeGroup" name="kelompok_material_id" required class="mt-2 w-full border rounded-xl px-4 py-3"><option value="">Pilih kelompok</option>@foreach($kelompok as $group)<option value="{{ $group->id }}">{{ $group->nama }}</option>@endforeach</select><label class="block text-xs font-black text-gray-400 uppercase mt-4">Satuan pencatatan</label><select id="typeUnit" name="satuan_pencatatan" required class="mt-2 w-full border rounded-xl px-4 py-3"><option value="KG">KG</option><option value="PCS">PCS</option></select><div class="flex gap-3 mt-6"><button type="button" onclick="typeModal.classList.add('hidden')" class="flex-1 bg-gray-100 rounded-xl py-3 font-bold">Batal</button><button class="flex-1 bg-emerald-600 text-white rounded-xl py-3 font-bold">Simpan</button></div></form></div>
@push('scripts')<script>function openType(item=null){typeTitle.textContent=item?'Edit Jenis Sampah':'Tambah Jenis Sampah';typeForm.action=item?@json(url('/jenis-sampah'))+'/'+item.id:@json(route('jenis-sampah.store'));typeMethod.value=item?'PUT':'POST';typeName.value=item?.name||'';typeGroup.value=item?.group||'';typeUnit.value=item?.unit||'KG';typeModal.classList.remove('hidden');typeModal.classList.add('flex')}</script>@endpush
@endsection
